title: Eray AYDIN
description: >
  Senior Web Developer, Junior Game Developer and Archy Linux System Administrator's Development and Life Journal
email: aydineray@mail.com
url: "http://erayaydin.github.io"
twitter_username: erayaydi
github_username:  erayaydin

paginate: 2
paginate_path: "/blog/:num/"

collections:
  categories:
    output: true
    permalink: /category/:slug/

defaults:
  -
    scope:
      path: ""
      type: categories
    values:
      layout: categories

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
permalink: :slug
